version: '3.7'

services:
    php-nginx:
        image: webdevops/php-nginx:8.2-alpine
        ports:
            - 80:80
        volumes:
            - ./www:/app

    mariadb:
        image: mariadb:10.6.8
        volumes:
            - vol-mariadb:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "secret"
            MYSQL_USER: "zyacbt"
            MYSQL_PASSWORD: "zyacbt"
            MYSQL_DATABASE: "zyacbt"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb:db
        ports:
            - 8181:80

volumes:
    vol-mariadb:	